# general setting
name: coe_scape
backend: dp # DataParallel
type: CoeModel
num_gpu: auto
manual_seed: 1234
attention: true

# path
path:
  resume_state: ~

# datasets
datasets:
  train_dataset:
    name: ScapeTrain
    type: PairScapeDataset
    phase: train
    data_root: ../data/SCAPE_r
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: False
    return_dist: False
  test_dataset:
    name: ScapeTest
    type: PairScapeDataset
    phase: test
    data_root: ../data/SCAPE_r
    return_evecs: True
    return_faces: True
    num_evecs: 200
    return_corr: True
    return_dist: True
  # setting for train dataset
  batch_size: 1
  num_worker: 16

# network setting
networks:
  feature_extractor:
    type: ASAP_DiffusionNet
    in_channels: 128
    out_channels: 80
    C_width: 128
    N_block: 4
  attention:
    type: CrossAttentionRefinementNet
    n_in: 80
    num_head: 4
    gnn_dim: 128
    n_layers: 1

# training setting
train:
  total_epochs: 50
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 50
  losses:
    consistent_loss:
      type: ConsistentLoss
      mu_off: 1
      mu_pos: 50
      mu_ortho: 1000
      A_ortho: true

# validation setting
val:
  val_freq: 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 4000